name: Android CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Install Android SDK Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y zipalign


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Retrieve version name
      run: echo VERSION_NAME=$(date "+%Y%m%d")_$(echo ${{ github.event.head_commit.id }} | head -c 7) >> $GITHUB_ENV

    - name: Retrieve version code
      run: echo VERSION_CODE=$(cat ${{ github.workspace }}/app/build.gradle | grep "versionCode" | grep -Eo "[0-9]+") >> $GITHUB_ENV

    - name: Set version name
      run: sed -i "s/versionName \".*\"/versionName \"${{ env.VERSION_NAME }}\"/" ${{ github.workspace }}/app/build.gradle
      
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Generate debug keystore
      run: |
        keytool -genkeypair -alias androiddebugkey \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -keystore debug.keystore \
          -storepass android -keypass android \
          -dname "CN=Debug,O=CI,C=US"

    - name: Sign APK
      run: |
         jarsigner -verbose -keystore debug.keystore \
           -storepass android -keypass android \
           -signedjar ${{ github.workspace }}/app/build/outputs/apk/release/app-release-signed.apk \
           ${{ github.workspace }}/app/build/outputs/apk/release/app-release-unsigned.apk androiddebugkey
  
    - name: Zipalign APK
      run: |
        zipalign -f 4 \
          $GITHUB_WORKSPACE/app/build/outputs/apk/release/app-release-signed.apk \
          $GITHUB_WORKSPACE/app/build/outputs/apk/release/app-release-aligned.apk

    - name: Rename
      run: mv ${{ github.workspace }}/app/build/outputs/apk/release/app-release-aligned.apk ${{ github.workspace }}/app/build/outputs/apk/release/fcmfix-ci-${{ env.VERSION_NAME }}.apk
    
    - name: Upload built apk
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: ${{ github.workspace }}/app/build/outputs/apk/release/fcmfix-ci-${{ env.VERSION_NAME }}.apk
  
